version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    # Update all dependencies
    allow:
      - dependency-type: "all"
        # Exclude certain packages from updates
        # exclude:
        #   - package-name: "package1"
        #     dependency-type: "all"
        #   - package-name: "package2"
        #     dependency-type: "all"
    # Use a custom command to update dependencies
    # ignore-differences: true
    # commands:
    #   - "yarn install"
    #   - "yarn upgrade"
